version: 2
updates:
  - package-ecosystem: gradle
    labels:
      - dependencies
    assignees:
      - 'OptimumCode'
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    labels:
      - dependencies
      - CI/CD
    assignees:
      - 'OptimumCode'
    directory: '/'
    schedule:
      interval: daily