name: Bug
description: Report an issue with the library
title: 'Bug: <title>'
labels:
  - bug
assignees:
  - OptimumCode
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: JSON schema
      description: A JSON schema that results in the observed behavior
      placeholder: |
        {}
      render: json
    validations:
      required: false
  - type: input
    attributes:
      label: Library version
      description: Version of the library which you used when experienced the problem
      placeholder: '0.0.1'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
