name: Check project

on:
  workflow_call:
    inputs:
      run-on:
        type: string
        required: true
        description: "runner to check the project"
      task:
        type: string
        required: true
        description: "task to check the platform targets"
      remote-schema-artifact:
        type: string
        required: true
        description: "artifact with remote schemas generated for tests"

jobs:
  check:
    runs-on: ${{ inputs.run-on }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .ci-java-version
      - uses: actions/setup-python@v5
        with:
          python-version-file: .ci-python-version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: Cache konan
        uses: actions/cache@v3.3.2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.remote-schema-artifact }}
          path: test-suites/build/
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.11.1
        with:
          gradle-version: wrapper
          arguments: |
            --no-daemon
            --info
            ${{ inputs.task }}
            detektAll
            ktlintCheck
            apiCheck
            -x
            :test-suites:generateRemoteSchemas