name: Check project

on:
  workflow_call:
    inputs:
      run-on:
        type: string
        required: true
        description: "runner to check the project"
      task:
        type: string
        required: true
        description: "task to check the platform targets"
      upload-code-coverage:
        type: boolean
        description: "enabled uploading coverage report to codecov"
        required: false
        default: false

jobs:
  check:
    runs-on: ${{ inputs.run-on }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .ci-java-version
      - uses: actions/setup-python@v5
        with:
          python-version-file: .ci-python-version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: Cache konan
        uses: actions/cache@v3.3.2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.11.1
        with:
          gradle-version: wrapper
          arguments: |
            --no-daemon
            --info
            ${{ inputs.task }}
            detektAll
            ktlintCheck
            apiCheck
            koverXmlReport
      - name: Upload coverage reports to Codecov
        if: inputs.upload-code-coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}