name: Upload code coverage results

on:
  workflow_run:
    workflows: ['Check the PR']
    types: [completed]

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.actor.name != 'dependabot[bot]' && github.repository == 'OptimumCode/json-schema-validator'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Download benchmark results
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: reports/
          run-id: ${{ github.event.workflow_run.id }}
      - name: Download PR number
        uses: actions/download-artifact@v4
        with:
          name: pr-number
          path: '.'
          run-id: ${{ github.event.workflow_run.id }}
      - id: trigger
        run: echo "pr-number=$(cat pr_number)" >> GITHUB_OUTPUT
      - name: Test pull_requests objects
        run: echo ${{ github.event.workflow_run.pull_requests }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          override_pr: ${{ steps.trigger.outputs.pr-number }}
          token: ${{ secrets.CODECOV_TOKEN }}