name: Upload code coverage results

on:
  workflow_run:
    workflows: ['Check the PR']
    types: [completed]

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.actor.name != 'dependabot[bot]' && github.repository == 'OptimumCode/json-schema-validator'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Download benchmark results
        uses: dawidd6/action-download-artifact@v6
        with:
          name: coverage-reports
          path: reports/
          run_id: ${{ github.event.workflow_run.id }}
      - name: Download PR number
        uses: dawidd6/action-download-artifact@v6
        with:
          name: pr-number
          path: '.'
          run_id: ${{ github.event.workflow_run.id }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          override_branch: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          override_commit: ${{ github.event.workflow_run.pull_requests[0].head.sha }}
          override_pr: ${{ github.event.workflow_run.pull_requests[0].number }}
          token: ${{ secrets.CODECOV_TOKEN }}