name: Execute FOSSA analyze action

on:
  pull_request_target:
    branches:
      - main

jobs:
  dump-unicode-data:
    uses: ./.github/workflows/unicode-dump.yml
  fossa-scan:
    runs-on: ubuntu-latest
    needs:
      - dump-unicode-data
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .java-version
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache unicode data
        uses: actions/cache@v4
        with:
          fail-on-cache-miss: true
          path: unicode_dump
          key: unicode-dump-${{ hashFiles('unicode_dump/*') }}
          restore-keys: |
            unicode-dump-
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Install fossa cli
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash"
      - name: Run FOSSA analyze
        run: fossa analyze --project git+github.com/OptimumCode/json-schema-validator --branch ${{ github.event.pull_request.head.ref }}
        env:
          FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}
      - name: Run FOSSA analyze
        run: fossa test --project git+github.com/OptimumCode/json-schema-validator
        env:
          FOSSA_API_KEY: ${{secrets.FOSSA_API_KEY}}