name: Reusable workflow to run a benchmark on the platform

on:
  workflow_call:
    inputs:
      run-on:
        type: string
        required: true
        description: "runner to check the project"
      additional-task:
        type: string
        description: additional task to add to gradle call
        required: false
        default: ""

jobs:
  benchmark:
    runs-on: ${{ inputs.run-on }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .ci-java-version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - run: ./gradlew --no-daemon --info :benchmark:benchmark ${{ inputs.additional-task }}