name: Reusable workflow to run a benchmark on the platform

on:
  workflow_call:
    inputs:
      run-on:
        type: string
        required: true
        description: "runner to check the project"
      additional-task:
        type: string
        description: additional task to add to gradle call
        required: false
        default: ""
      warmups:
        description: 'number of warmups run before the actual benchmark'
        type: string
        required: false
      iterations:
        description: 'number of iterations in the benchmark'
        type: string
        required: false
      iteration-time:
        description: 'duration of individual integration in benchmark'
        type: string
        required: false
      iteration-time-unit:
        description: 'timeunit for iteration-time parameter'
        default: 's'
        type: string
        required: false

jobs:
  benchmark:
    runs-on: ${{ inputs.run-on }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .ci-java-version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Run benchmarks
        run: >
          ./gradlew --no-daemon --info :benchmark:benchmark ${{ inputs.additional-task }}
          -Pbenchmark_warmups=${{ inputs.warmups }}
          -Pbenchmark_iterations=${{ inputs.iterations }}
          -Pbenchmark_iteration_time=${{ inputs.iteration-time }}
          -Pbenchmark_iteration_time_unit=${{ inputs.iteration-time-unit }}