name: "Create release"

on:
  workflow_dispatch:

env:
  VERSION_FILE: gradle.properties
  VERSION_PATTERN: '(?<=version=).+'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      CURRENT_VERSION: ${{ steps.versions.outputs.CURRENT_VERSION }}
      NEXT_VERSION: ${{ steps.versions.outputs.NEXT_VERSION }}
      RELEASE_VERSION: ${{ steps.versions.outputs.RELEASE_VERSION }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Get version
        id: versions
        uses: HardNorth/github-version-generate@v1.4.0
        with:
          version-source: file
          version-file: ${{ env.VERSION_FILE }}
          version-file-extraction-pattern: ${{ env.VERSION_PATTERN }}
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
  publish_artifacts:
    needs:
      - version
      - build-and-test
    runs-on: macos-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .java-version
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache unicode data
        uses: actions/cache@v4
        with:
          path: unicode_dump
          key: unicode-dump-${{ hashFiles('unicode_dump/*') }}
          restore-keys: |
            unicode-dump-
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Build and publish release
        run: >
          ./gradlew --no-daemon --info :json-schema-validator:assemble
          publish closeAndReleaseStagingRepositories
          -Pversion=${{ needs.version.outputs.RELEASE_VERSION }}
          -x :benchmark:benchmark
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  create_release:
    runs-on: ubuntu-latest
    needs:
      - publish_artifacts
      - version
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Store SHA of HEAD commit on ENV
        run: echo "GIT_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create tag
        id: create_tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PUSH_PAT }}
          script: |
            const {GIT_HEAD} = process.env
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ needs.version.outputs.RELEASE_VERSION }}",
              sha: `${GIT_HEAD}`
            })

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: changelog_config.json
          toTag: ${{ needs.version.outputs.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          name: Release ${{ needs.version.outputs.RELEASE_VERSION }}
          tag: ${{ needs.version.outputs.RELEASE_VERSION }}
          token: ${{ secrets.PUSH_PAT }}
          makeLatest: ${{ github.ref == 'refs/heads/main' }}
  update-version:
    runs-on: ubuntu-latest
    needs:
      - create_release
      - version
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PUSH_PAT }}
    - name: Prepare next dev version
      id: prepare_next_dev
      run: |
        sed -i -e 's/${{ needs.version.outputs.CURRENT_VERSION }}/${{ needs.version.outputs.NEXT_VERSION }}/g' gradle.properties
        sed -i -E -e 's/json-schema-validator(:|\/)[0-9]+\.[0-9]+\.[0-9]+/json-schema-validator\1${{ needs.version.outputs.RELEASE_VERSION }}/g' README.md
        sed -i -E -e 's/json-schema-validator(:|\/)[0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)/json-schema-validator\1${{ needs.version.outputs.NEXT_VERSION }}/g' README.md
    - name: Commit next dev version
      id: commit_next_dev
      uses: EndBug/add-and-commit@v9
      with:
        add: "['gradle.properties', 'README.md']"
        default_author: github_actions
        message: "Prepare next version"