name: Publish snapshot

on:
  push:
    branches:
      - main
      - issue_#1 # test snapshots

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: .ci-java-version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Cache konan
        uses: actions/cache@v3.3.1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        with:
          gradle-version: wrapper
          arguments: |
            --no-daemon
            build
            publish