name: Publish snapshot

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'changelog_config.json'
      - 'README.md'
      - 'benchmark/*'
      - '.github/workflows/platform-benchmark.yml'
      - '.github/workflows/benchmark.yml'

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      upload-code-coverage: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs:
      - build-and-test
    runs-on: macos-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .java-version
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache unicode data
        uses: actions/cache@v4
        with:
          path: unicode_dump
          key: unicode-dump-${{ hashFiles('unicode_dump/*') }}
          restore-keys: |
            unicode-dump-
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Setup Gradle
        run: >
          ./gradlew
          --no-daemon
          --info
          :assemble
          publish
          -x :benchmark:benchmark
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}