name: Publish snapshot

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version-file: .ci-java-version
      - uses: actions/setup-python@v5
        with:
          python-version-file: .ci-python-version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: Cache konan
        uses: actions/cache@v3.3.2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.11.1
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        with:
          gradle-version: wrapper
          arguments: |
            --no-daemon
            --info
            build
            publish